### ISSUE TITLE
Private Chat 

### ISSUE THREAD

**Issue by MonMohon** [ably-labs/laravel-broadcast-app#20]
please help how to create private channel and also I could not find <chat-component> in chatRoom.blade

**Comment by sacOO7** [comment]
Are you asking how to create private channel from UI? Are you able to run the app. I would recommend running the app inside docker

**Comment by MonMohon** [comment]
yes it works fine no issue

**Comment by MonMohon** [comment]
Actually I'm working on Food Delivery App
Backend: Laravel
Frontend: React, React Native
ws: Ably

**Comment by sacOO7** [comment]
As per https://github.com/ably-labs/laravel-broadcast-app/blob/3ae9b9b97e05c1394bf128ae4dd905e245c7db71/routes/channels.php#L20, private channels can only be created in the format room-1, room-2, room-3 etc. 
This is also explicitly mentioned on the UI while creating the room.

**Comment by sacOO7** [comment]
Same room is also used for presence. Internally we create presence channels using the same room name and above method is used to authenticate the presence channels as well.

**Comment by sacOO7** [comment]
Also, you might like to go through https://laravel.com/docs/11.x/broadcasting as well as doc mentioned here https://github.com/ably/laravel-broadcaster.

**Comment by MonMohon** [comment]
ok thanks

**Comment by sacOO7** [comment]
You won't be able to understand enough by just looking at the source code

**Comment by MonMohon** [comment]
yes very true source code is just implement with ably
anyway thanks and close the issue

**Comment by sacOO7** [comment]
Thanks, please do raise the issue on https://github.com/ably/laravel-broadcaster if you face any problems in the future.
